# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-18 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
